version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo-container
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 30s  # Gives MongoDB time to initialize before health check starts
      timeout: 10s

  backend:
    build: ./backend
    container_name: backend-container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongo-container:27017/mydatabase
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend-container
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo-data:
