# kustomize/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: prod

patches:
  - path: backend-v1-patch.yaml # Apply the backend patch
  - path: frontend-deployment-patch.yaml # Apply the frontend patch
  # Add more patches here if needed (e.g., for different secrets, ingress host, etc.)