# ------------------- MongoDB Secret -------------------
# Stores sensitive MongoDB credentials
apiVersion: v1
kind: Secret
metadata:
  name: app-secret # Name referenced by StatefulSet and Deployment
type: Opaque
data:
  # Provide base64 encoded username (e.g., echo -n 'root' | base64 => cm9vdA==)
  mongo-user: cm9vdA== # Replace with your base64 encoded user if not 'root'
  # Provide base64 encoded password (e.g., echo -n 'yourSuperSecretPassword' | base64 => eW91clN1cGVyU2VjcmV0UGFzc3dvcmQ=)
  mongo-password: <your-base64-encoded-password> # !!! REPLACE THIS !!!
---