# kustomize/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongo-secret.yaml
  - mongo-statefulset.yaml
  - mongo-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml # Or frontend.yaml
  - ingress.yaml