name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies for frontend and backend
        run: |
          cd frontend
          npm install
          cd ../backend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npm test -- --coverage --ci --silent

      - name: Build Docker images
        run: |
          docker build -t moizz407/devops-assignment-frontend ./frontend
          docker build -t moizz407/devops-assignment-backend ./backend

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push frontend image to DockerHub
        run: |
          docker push moizz407/devops-assignment-frontend

      - name: Push backend image to DockerHub
        run: |
          docker push moizz407/devops-assignment-backend
